/*!
 * @AIMMS_FILE=models/PageMenuOptions/WNVTestModel.aimms
 */

scenario(
	"Assert information of each of the page link listed in Page Menu when identifier is configured",
	() => {
		loadPage("Main Project/Map Test");

		getPageMenu()
			.getMenuLinksInfo()
			.should.beEqualTo([
				{
					DisplayName: "Network Page",
					Slug: "new_map_test_after_fix",
					Tooltip: "Map Widget",
					PageType: "pagev2-grid",
					Link: "Main Project/New Map Test After Fix",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Home Page",
					Slug: "home",
					Tooltip: "Home",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test",
					IsSelected: true,
					HasChildren: true,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 1",
					Slug: "new_page_1",
					Tooltip: "Child Page 1",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (1)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 2",
					Slug: "new_page_2",
					Tooltip: "Child Page 2",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (2)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 3",
					Slug: "new_page_3",
					Tooltip: "Child Page 3",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (3)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Charts Page",
					Slug: "highchart_page",
					Tooltip: "Charts",
					PageType: "pagev2-grid",
					Link: null,
					IsSelected: false,
					HasChildren: false,
					IsActive: false,
				},
				{
					DisplayName: "Multiple Widgets",
					Slug: "various_widgets",
					Tooltip: "All WIdgets",
					PageType: "pagev2-grid",
					Link: "Main Project/Various Widgets",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Demo Page",
					Slug: "demo_page",
					Tooltip: "Demo Widgets",
					PageType: "pagev2-grid",
					Link: "Main Project/Demo Page",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "4856",
					Slug: "ticket4856",
					Tooltip: "Bug 4856",
					PageType: "pagev2-grid",
					Link: "Main Project/Ticket4856",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "4849",
					Slug: "ticket4849",
					Tooltip: "Bug 4849",
					PageType: "pagev2-grid",
					Link: "Main Project/Ticket4849",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "4862",
					Slug: "ticket4862",
					Tooltip: "",
					PageType: "pagev2-grid",
					Link: null,
					IsSelected: false,
					HasChildren: false,
					IsActive: false,
				},
			]);

		getPageMenu().navigateToPage("Main Project/New Map Test After Fix");

		getPageMenu()
			.getMenuLinksInfo()
			.should.beEqualTo([
				{
					DisplayName: "Network Page@123",
					Slug: "new_map_test_after_fix",
					Tooltip: "Map Widget",
					PageType: "pagev2-grid",
					Link: "Main Project/New Map Test After Fix",
					IsSelected: true,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Home Page",
					Slug: "home",
					Tooltip: "Home",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test",
					IsSelected: false,
					HasChildren: true,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 1",
					Slug: "new_page_1",
					Tooltip: "Child Page 1",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (1)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 2",
					Slug: "new_page_2",
					Tooltip: "Child Page 2",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (2)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 3",
					Slug: "new_page_3",
					Tooltip: "Child Page 3",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (3)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 4",
					Slug: "new_page_4",
					Tooltip: "Child Page 4",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (4)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 5",
					Slug: "new_page_5",
					Tooltip: "Child Page 5",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (5)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 6",
					Slug: "new_page_6",
					Tooltip: "Child Page 6",
					PageType: "pagev2-grid",
					Link: null,
					IsSelected: false,
					HasChildren: false,
					IsActive: false,
				},
				{
					DisplayName: "Child Page 7",
					Slug: "new_page_7",
					Tooltip: "Child Page 7",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (7)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 8",
					Slug: "new_page_8",
					Tooltip: "Child Page 8",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (8)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 9",
					Slug: "new_page_9",
					Tooltip: "Child Page 9",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (9)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 11",
					Slug: "new_page_10",
					Tooltip: "Child Page 11",
					PageType: "pagev2-grid",
					Link: "Main Project/Map Test/new page (10)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 14",
					Slug: "new_page_3_1",
					Tooltip: "Child Page 14",
					PageType: "pagev2-grid",
					Link: "Main Project/Ticket4849/new page (3)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Charts Page",
					Slug: "highchart_page",
					Tooltip: "Charts",
					PageType: "pagev2-grid",
					Link: null,
					IsSelected: false,
					HasChildren: false,
					IsActive: false,
				},
				{
					DisplayName: "Multiple Widgets",
					Slug: "various_widgets",
					Tooltip: "All WIdgets",
					PageType: "pagev2-grid",
					Link: "Main Project/Various Widgets",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Demo Page",
					Slug: "demo_page",
					Tooltip: "Demo Widgets",
					PageType: "pagev2-grid",
					Link: "Main Project/Demo Page",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "4856",
					Slug: "ticket4856",
					Tooltip: "Bug 4856",
					PageType: "pagev2-grid",
					Link: "Main Project/Ticket4856",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "4849",
					Slug: "ticket4849",
					Tooltip: "Bug 4849",
					PageType: "pagev2-grid",
					Link: "Main Project/Ticket4849",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "4862",
					Slug: "ticket4862",
					Tooltip: "",
					PageType: "pagev2-grid",
					Link: null,
					IsSelected: false,
					HasChildren: true,
					IsActive: false,
				},
				{
					DisplayName: "Child Page 12",
					Slug: "new_page_1_1",
					Tooltip: "Child Page 12",
					PageType: "pagev2-grid",
					Link: "Main Project/Ticket4849/new page (1)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
				{
					DisplayName: "Child Page 13",
					Slug: "new_page_2_1",
					Tooltip: "Child Page 13",
					PageType: "pagev2-grid",
					Link: "Main Project/Ticket4849/new page (2)",
					IsSelected: false,
					HasChildren: false,
					IsActive: true,
				},
			]);
	}
);
