/*!
 * @AIMMS_FILE=models/PageV2/Vliegtuigjes/Vliegtuigjes.aimms
 */

scenario("When a widget is cut and pasted, asserting Style properties on App Manager.", () => {
	loadPage("Main Project/Book Corner/WH");

	// Open the App Manager.
	openAppManager();

	// Unfold Widget container of "Book Corner/WH" page
	getAppManager().unfoldWidgetContainers([
		"Main Project/Book Corner",
		"Main Project/Book Corner/WH",
	]);

	// Cut 'Book Bars' widget of 'Book Corner' page.
	getAppManager()
		.getFlyoutMenu({
			pagePath: "Main Project/Book Corner",
			widgetName: "Book Bars",
		})
		.clickOnCut();

	// Assert the Styles of App Manager Tree.
	getAppManager()
		.getAppManagerStylesInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveGrey100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite80.rgbaWithWhitespace,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "wh_subpage-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Legend",
				Slug: "Book Legend",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Table",
				Slug: "Book Table",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Bars",
				Slug: "Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Second Book Bars",
				Slug: "Second Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Selected Book Set",
				Slug: "Selected Book Set",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Cover",
				Slug: "Book Cover",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Author Portrait",
				Slug: "Author Portrait",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "WH",
				Slug: "mischapage_1",
				NodeType: "Page",
				IsNodeSelected: true,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite40.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "mischapage_1-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Headertje",
				Slug: "Headertje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Mooietekst",
				Slug: "Mooietekst",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Plaatje",
				Slug: "Plaatje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "JE",
				Slug: "je_1",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "öβå",
				Slug: "oeva",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
		]);

	// Paste the cut widget onto 'Book Corner/WH' page.
	getAppManager()
		.getFlyoutMenu({
			pagePath: "Main Project/Book Corner/WH",
		})
		.clickOnPasteWidget();

	// Assert the Styles of App Manager Tree.
	getAppManager()
		.getAppManagerStylesInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveGrey100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite80.rgbaWithWhitespace,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "wh_subpage-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Legend",
				Slug: "Book Legend",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Table",
				Slug: "Book Table",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Second Book Bars",
				Slug: "Second Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Selected Book Set",
				Slug: "Selected Book Set",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Cover",
				Slug: "Book Cover",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Author Portrait",
				Slug: "Author Portrait",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "WH",
				Slug: "mischapage_1",
				NodeType: "Page",
				IsNodeSelected: true,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite40.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "mischapage_1-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Headertje",
				Slug: "Headertje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Mooietekst",
				Slug: "Mooietekst",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Plaatje",
				Slug: "Plaatje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Bars",
				Slug: "Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "JE",
				Slug: "je_1",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "öβå",
				Slug: "oeva",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
		]);

	// Cut 'Plaatje' widget of 'Book Corner/WH' page.
	getAppManager()
		.getFlyoutMenu({
			pagePath: "Main Project/Book Corner/WH",
			widgetName: "Plaatje",
		})
		.clickOnCut();

	// Assert the Styles of App Manager Tree.
	getAppManager()
		.getAppManagerStylesInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveGrey100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite80.rgbaWithWhitespace,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "wh_subpage-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Legend",
				Slug: "Book Legend",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Table",
				Slug: "Book Table",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Second Book Bars",
				Slug: "Second Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Selected Book Set",
				Slug: "Selected Book Set",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Cover",
				Slug: "Book Cover",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Author Portrait",
				Slug: "Author Portrait",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "WH",
				Slug: "mischapage_1",
				NodeType: "Page",
				IsNodeSelected: true,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite40.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "mischapage_1-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Headertje",
				Slug: "Headertje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Mooietekst",
				Slug: "Mooietekst",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Plaatje",
				Slug: "Plaatje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Bars",
				Slug: "Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "JE",
				Slug: "je_1",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "öβå",
				Slug: "oeva",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
		]);

	// Paste the cut widget onto 'SidePanels' page.
	getAppManager()
		.getFlyoutMenu({
			pagePath: "Main Project/Book Corner",
		})
		.clickOnPasteWidget();

	// Assert the Styles of App Manager Tree.
	getAppManager()
		.getAppManagerStylesInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveGrey100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite80.rgbaWithWhitespace,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "wh_subpage-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Legend",
				Slug: "Book Legend",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Table",
				Slug: "Book Table",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Second Book Bars",
				Slug: "Second Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Selected Book Set",
				Slug: "Selected Book Set",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Cover",
				Slug: "Book Cover",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Author Portrait",
				Slug: "Author Portrait",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Plaatje",
				Slug: "Plaatje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "WH",
				Slug: "mischapage_1",
				NodeType: "Page",
				IsNodeSelected: true,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite40.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "mischapage_1-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Headertje",
				Slug: "Headertje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Mooietekst",
				Slug: "Mooietekst",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Bars",
				Slug: "Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "JE",
				Slug: "je_1",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "öβå",
				Slug: "oeva",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
		]);

	// Cut 'Author Portrait' widget of 'Book Corner' page.
	getAppManager()
		.getFlyoutMenu({
			pagePath: "Main Project/Book Corner",
			widgetName: "Author Portrait",
		})
		.clickOnCut();

	// Paste the cut widget back onto same page.
	getAppManager()
		.getFlyoutMenu({
			pagePath: "Main Project/Book Corner",
		})
		.clickOnPasteWidget();

	// Assert the Styles of App Manager Tree.
	getAppManager()
		.getAppManagerStylesInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveGrey100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite80.rgbaWithWhitespace,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "wh_subpage-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Book Legend",
				Slug: "Book Legend",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Table",
				Slug: "Book Table",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Second Book Bars",
				Slug: "Second Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Selected Book Set",
				Slug: "Selected Book Set",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Cover",
				Slug: "Book Cover",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Plaatje",
				Slug: "Plaatje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Author Portrait",
				Slug: "Author Portrait",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "WH",
				Slug: "mischapage_1",
				NodeType: "Page",
				IsNodeSelected: true,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite40.rgbaWithWhitespace,
			},
			{
				Name: "Widgets on page",
				Slug: "mischapage_1-widget-container",
				NodeType: "Container",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Headertje",
				Slug: "Headertje",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Mooietekst",
				Slug: "Mooietekst",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "Book Bars",
				Slug: "Book Bars",
				NodeType: "Widget",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveGrey100.clear.rgbaWithWhitespace,
			},
			{
				Name: "JE",
				Slug: "je_1",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "öβå",
				Slug: "oeva",
				NodeType: "Page",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				IsNodeSelected: false,
				ContentsColor: colors.colorPrimitiveWhite100.rgb,
				BackgroundColor: colors.colorPrimitiveTransparentWhite16.rgbaWithWhitespace,
			},
		]);
});
