/*!
 * @AIMMS_FILE=models/PageV2/AppManager/DialogPagev2.aimms
 */

scenario(
	"Post renaming few of Standard and Custom Grid-Layout Dialog Pages, asserting data on App Manager.",
	() => {
		loadPage("Main Project/home?aimms_only_persistence.write=true");

		// Unfold few of the pages
		openAppManager().unfoldWidgetContainers([
			"Main Project/Standard Grid Layout Dialogs/Grid Layout 11 Dialog/Dummy Grid Layout Dialog",
			"Main Project/Standard Grid Layout Dialogs/Another Grid Layout 11 Dialog",
			"Main Project/Custom Grid Layout Dialog/Custom Grid Layout Dialog 2",
			"Main Project/Custom Grid Layout Dialog/Another Custom Grid Layout Dialog",
		]);

		getAppManager()
			.getFlyoutMenu({
				pagePath: "Main Project/Standard Grid Layout Dialogs/Another Grid Layout 11 Dialog",
			})
			.clickOnRename()
			.enterName("SGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze")
			.pressKeys([SPECIAL_KEYS.enter]);

		getAppManager()
			.getFlyoutMenu({
				pagePath:
					"Main Project/Custom Grid Layout Dialog/Another Custom Grid Layout Dialog",
			})
			.clickOnRename()
			.enterName("CGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze")
			.pressKeys([SPECIAL_KEYS.enter]);

		getAppManager()
			.getAppManagerInfo()
			.should.eql([
				{
					Name: "Main Project",
					Slug: "main_project",
					NodeType: "Pagev2-grid",
					Tooltip: "Main Project",
					NodeState: "Expanded",
					Icon: "",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "home",
					Slug: "home",
					NodeType: "Page",
					Tooltip: "home [ Classic Page ]",
					NodeState: "Collapsed",
					Icon: "icon-home",
					IsNodeSelected: true,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Standard Grid Layout Dialogs",
					Slug: "standard_grid_layout_dialogs",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "Standard Grid Layout Dialogs [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "standard_grid_layout_dialogs-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Collapsed",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Grid Layout 11 Dialog",
					Slug: "grid_layout_11_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "Grid Layout 11 Dialog [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "grid_layout_11_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Collapsed",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Dummy Grid Layout Dialog",
					Slug: "dummy_grid_layout_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "Dummy Grid Layout Dialog [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "dummy_grid_layout_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Expanded",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "widget1_v2 (1) (1) (1)",
					Slug: "widget1_v2_1_1_1",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (1) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "table_Test_v2 (1) (1) (1)",
					Slug: "table_Test_v2_1_1_1",
					NodeType: "Widget",
					Tooltip: "table_Test_v2 (1) (1) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "widget1_1_v2 (1) (1) (1)",
					Slug: "widget1_1_v2_1_1_1",
					NodeType: "Widget",
					Tooltip: "widget1_1_v2 (1) (1) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "SGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze",
					Slug: "another_grid_layout_11_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "SGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "1",
					Slug: "another_grid_layout_11_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Expanded",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "widget1_v2 (1) (2)",
					Slug: "widget1_v2_1_2",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (2) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "Custom Grid Layout Dialog",
					Slug: "custom_grid_layout_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "Custom Grid Layout Dialog [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "custom_grid_layout_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Collapsed",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Custom Grid Layout Dialog 2",
					Slug: "custom_grid_layout_dialog_2",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "Custom Grid Layout Dialog 2 [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "custom_grid_layout_dialog_2-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Expanded",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "widget1_v2 (1) (1) (2) (1)",
					Slug: "widget1_v2_1_1_2_1",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (1) (2) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "table_Test_v2 (1) (1) (2) (1)",
					Slug: "table_Test_v2_1_1_2_1",
					NodeType: "Widget",
					Tooltip: "table_Test_v2 (1) (1) (2) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "widget1_1_v2 (1) (1) (2) (1)",
					Slug: "widget1_1_v2_1_1_2_1",
					NodeType: "Widget",
					Tooltip: "widget1_1_v2 (1) (1) (2) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "CGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze",
					Slug: "another_custom_grid_layout_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "CGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "2",
					Slug: "another_custom_grid_layout_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Expanded",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "widget1_v2 (1) (1) (2) (2)",
					Slug: "widget1_v2_1_1_2_2",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (1) (2) (2) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "widget1_v2 (1) (1) (2) (3)",
					Slug: "widget1_v2_1_1_2_3",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (1) (2) (3) [ Widget ]",
					WidgetState: "",
				},
			]);

		getAppManager()
			.getFlyoutMenu({
				pagePath: "Main Project/Standard Grid Layout Dialogs",
			})
			.clickOnRename()
			.enterName("SGLDP1 āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze")
			.pressKeys([SPECIAL_KEYS.enter]);

		getAppManager()
			.getFlyoutMenu({
				pagePath: "Main Project/Custom Grid Layout Dialog",
			})
			.clickOnRename()
			.enterName("CGLDP1 āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze")
			.pressKeys([SPECIAL_KEYS.enter]);

		getAppManager()
			.getAppManagerInfo()
			.should.eql([
				{
					Name: "Main Project",
					Slug: "main_project",
					NodeType: "Pagev2-grid",
					Tooltip: "Main Project",
					NodeState: "Expanded",
					Icon: "",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "home",
					Slug: "home",
					NodeType: "Page",
					Tooltip: "home [ Classic Page ]",
					NodeState: "Collapsed",
					Icon: "icon-home",
					IsNodeSelected: true,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "SGLDP1 āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze",
					Slug: "standard_grid_layout_dialogs",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "SGLDP1 āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "standard_grid_layout_dialogs-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Collapsed",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Grid Layout 11 Dialog",
					Slug: "grid_layout_11_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "Grid Layout 11 Dialog [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "grid_layout_11_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Collapsed",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Dummy Grid Layout Dialog",
					Slug: "dummy_grid_layout_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "Dummy Grid Layout Dialog [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "dummy_grid_layout_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Expanded",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "widget1_v2 (1) (1) (1)",
					Slug: "widget1_v2_1_1_1",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (1) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "table_Test_v2 (1) (1) (1)",
					Slug: "table_Test_v2_1_1_1",
					NodeType: "Widget",
					Tooltip: "table_Test_v2 (1) (1) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "widget1_1_v2 (1) (1) (1)",
					Slug: "widget1_1_v2_1_1_1",
					NodeType: "Widget",
					Tooltip: "widget1_1_v2 (1) (1) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "SGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze",
					Slug: "another_grid_layout_11_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "SGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "1",
					Slug: "another_grid_layout_11_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Expanded",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "widget1_v2 (1) (2)",
					Slug: "widget1_v2_1_2",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (2) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "CGLDP1 āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze",
					Slug: "custom_grid_layout_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "CGLDP1 āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "custom_grid_layout_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Collapsed",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Custom Grid Layout Dialog 2",
					Slug: "custom_grid_layout_dialog_2",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "Custom Grid Layout Dialog 2 [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "3",
					Slug: "custom_grid_layout_dialog_2-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Expanded",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "widget1_v2 (1) (1) (2) (1)",
					Slug: "widget1_v2_1_1_2_1",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (1) (2) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "table_Test_v2 (1) (1) (2) (1)",
					Slug: "table_Test_v2_1_1_2_1",
					NodeType: "Widget",
					Tooltip: "table_Test_v2 (1) (1) (2) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "widget1_1_v2 (1) (1) (2) (1)",
					Slug: "widget1_1_v2_1_1_2_1",
					NodeType: "Widget",
					Tooltip: "widget1_1_v2 (1) (1) (2) (1) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "CGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze",
					Slug: "another_custom_grid_layout_dialog",
					NodeType: "Pagev2-grid-dialog",
					Tooltip: "CGLDP āæśṣḍ ēr̥ṅṭñḥ ṇṁūīōl̥ D'Souze [ Dialog ]",
					NodeState: "Expanded",
					Icon: "pagev2-grid-dialog",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "Widgets on page",
					WidgetsCount: "2",
					Slug: "another_custom_grid_layout_dialog-widget-container",
					NodeType: "Container",
					Tooltip: "Widgets on page",
					NodeState: "Expanded",
					Icon: "aimms-cube2",
					IsNodeSelected: false,
					NodeHasHiddenIndication: false,
				},
				{
					Name: "widget1_v2 (1) (1) (2) (2)",
					Slug: "widget1_v2_1_1_2_2",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (1) (2) (2) [ Widget ]",
					WidgetState: "",
				},
				{
					Name: "widget1_v2 (1) (1) (2) (3)",
					Slug: "widget1_v2_1_1_2_3",
					NodeType: "Widget",
					Tooltip: "widget1_v2 (1) (1) (2) (3) [ Widget ]",
					WidgetState: "",
				},
			]);
	}
);
