/*!
 * @AIMMS_FILE=models/PageV2/Vliegtuigjes/Vliegtuigjes.aimms
 */

scenario("On a PageV2 app, checking for data on App Manager.", () => {
	loadPage("Main Project/home");

	// Open the App Manager. Assert the information shown.
	openAppManager()
		.getAppManagerInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				Tooltip: "Main Project",
				NodeState: "Expanded",
				Icon: "",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				Tooltip: "home [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-home",
				IsNodeSelected: true,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				Tooltip: "Another Page [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				Tooltip: "Button Page [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				Tooltip: "Book Corner [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				Tooltip: "Test Page [ Page ]",
				NodeState: "Collapsed",
				Icon: "icon-grid6",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				Tooltip: "SidePanels [ Classic Side Panel ]",
				NodeState: "Collapsed",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				Tooltip: "Dialog Pages [ Classic Dialog ]",
				NodeState: "Collapsed",
				Icon: "icon-popout",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
		]);

	// Unfold few of the pages
	getAppManager().unfoldPageNodes([
		"Main Project/home",
		"Main Project/Another Page",
		"Main Project/Button Page",
	]);

	getAppManager().unfoldWidgetContainers([
		"Main Project/home",
		"Main Project/Another Page",
		"Main Project/Button Page",
	]);

	// Assert the information shown on App Manager.
	getAppManager()
		.getAppManagerInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				Tooltip: "Main Project",
				NodeState: "Expanded",
				Icon: "",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				Tooltip: "home [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-home",
				IsNodeSelected: true,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "6",
				Slug: "home-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "gfdgfd",
				Slug: "gfdgfd",
				NodeType: "Widget",
				Tooltip: "gfdgfd [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Groupie1",
				Slug: "Groupie1",
				NodeType: "Widget",
				Tooltip: "Groupie1 [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "yfhtye",
				Slug: "yfhtye",
				NodeType: "Widget",
				Tooltip: "yfhtye [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "BOE",
				Slug: "BOE",
				NodeType: "Widget",
				Tooltip: "BOE [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "ggggfhfgdh",
				Slug: "ggggfhfgdh",
				NodeType: "Widget",
				Tooltip: "ggggfhfgdh [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "flagsonhome",
				Slug: "flagsonhome",
				NodeType: "Widget",
				Tooltip: "flagsonhome [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				Tooltip: "Another Page [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "3",
				Slug: "another_page-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "ImportTable",
				Slug: "ImportTable",
				NodeType: "Widget",
				Tooltip: "ImportTable [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Selected Country",
				Slug: "Selected Country",
				NodeType: "Widget",
				Tooltip: "Selected Country [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "CalendarTableNowWorkingReally",
				Slug: "CalendarTableNowWorkingReally",
				NodeType: "Widget",
				Tooltip: "CalendarTableNowWorkingReally [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				Tooltip: "Button Page [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "4",
				Slug: "button_page-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "MyButton",
				Slug: "MyButton",
				NodeType: "Widget",
				Tooltip: "MyButton [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "B2",
				Slug: "B2",
				NodeType: "Widget",
				Tooltip: "B2 [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "B3",
				Slug: "B3",
				NodeType: "Widget",
				Tooltip: "B3 [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "B4",
				Slug: "B4",
				NodeType: "Widget",
				Tooltip: "B4 [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				Tooltip: "Book Corner [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				Tooltip: "Test Page [ Page ]",
				NodeState: "Collapsed",
				Icon: "icon-grid6",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				Tooltip: "SidePanels [ Classic Side Panel ]",
				NodeState: "Collapsed",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				Tooltip: "Dialog Pages [ Classic Dialog ]",
				NodeState: "Collapsed",
				Icon: "icon-popout",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
		]);

	// Unfold few more pages
	getAppManager().unfoldPageNodes(["Main Project/Book Corner/WH", "Main Project/Book Corner/JE"]);

	getAppManager().unfoldWidgetContainers([
		"Main Project/Book Corner/WH",
		"Main Project/Book Corner/JE",
	]);

	// Assert the information shown on App Manager.
	getAppManager()
		.getAppManagerInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				Tooltip: "Main Project",
				NodeState: "Expanded",
				Icon: "",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				Tooltip: "home [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-home",
				IsNodeSelected: true,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "6",
				Slug: "home-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "gfdgfd",
				Slug: "gfdgfd",
				NodeType: "Widget",
				Tooltip: "gfdgfd [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Groupie1",
				Slug: "Groupie1",
				NodeType: "Widget",
				Tooltip: "Groupie1 [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "yfhtye",
				Slug: "yfhtye",
				NodeType: "Widget",
				Tooltip: "yfhtye [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "BOE",
				Slug: "BOE",
				NodeType: "Widget",
				Tooltip: "BOE [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "ggggfhfgdh",
				Slug: "ggggfhfgdh",
				NodeType: "Widget",
				Tooltip: "ggggfhfgdh [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "flagsonhome",
				Slug: "flagsonhome",
				NodeType: "Widget",
				Tooltip: "flagsonhome [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				Tooltip: "Another Page [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "3",
				Slug: "another_page-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "ImportTable",
				Slug: "ImportTable",
				NodeType: "Widget",
				Tooltip: "ImportTable [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Selected Country",
				Slug: "Selected Country",
				NodeType: "Widget",
				Tooltip: "Selected Country [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "CalendarTableNowWorkingReally",
				Slug: "CalendarTableNowWorkingReally",
				NodeType: "Widget",
				Tooltip: "CalendarTableNowWorkingReally [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				Tooltip: "Button Page [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "4",
				Slug: "button_page-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "MyButton",
				Slug: "MyButton",
				NodeType: "Widget",
				Tooltip: "MyButton [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "B2",
				Slug: "B2",
				NodeType: "Widget",
				Tooltip: "B2 [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "B3",
				Slug: "B3",
				NodeType: "Widget",
				Tooltip: "B3 [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "B4",
				Slug: "B4",
				NodeType: "Widget",
				Tooltip: "B4 [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				Tooltip: "Book Corner [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "7",
				Slug: "wh_subpage-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Collapsed",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "WH",
				Slug: "mischapage_1",
				NodeType: "Page",
				Tooltip: "WH [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "3",
				Slug: "mischapage_1-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Headertje",
				Slug: "Headertje",
				NodeType: "Widget",
				Tooltip: "Headertje [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Mooietekst",
				Slug: "Mooietekst",
				NodeType: "Widget",
				Tooltip: "Mooietekst [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Plaatje",
				Slug: "Plaatje",
				NodeType: "Widget",
				Tooltip: "Plaatje [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "JE",
				Slug: "je_1",
				NodeType: "Page",
				Tooltip: "JE [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "3",
				Slug: "je_1-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Header",
				Slug: "Header",
				NodeType: "Widget",
				Tooltip: "Header [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Excerpt",
				Slug: "Excerpt",
				NodeType: "Widget",
				Tooltip: "Excerpt [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Scene",
				Slug: "Scene",
				NodeType: "Widget",
				Tooltip: "Scene [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "öβå",
				Slug: "oeva",
				NodeType: "Page",
				Tooltip: "öβå [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				Tooltip: "Test Page [ Page ]",
				NodeState: "Collapsed",
				Icon: "icon-grid6",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				Tooltip: "SidePanels [ Classic Side Panel ]",
				NodeState: "Collapsed",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				Tooltip: "Dialog Pages [ Classic Dialog ]",
				NodeState: "Collapsed",
				Icon: "icon-popout",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
		]);

	// Scroll and unfold few more pages
	getAppManager()
		.collapseAllNodes()
		.unfoldPageNodes([
			"Main Project/Test Page/Custom Grid Page",
			"Main Project/Test Page/Classic Layout Page",
			"Main Project/Test Page/A Grid Page But Hidden",
		]);

	// Assert the information shown on App Manager.
	getAppManager()
		.getAppManagerInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				Tooltip: "Main Project",
				NodeState: "Expanded",
				Icon: "",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				Tooltip: "home [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-home",
				IsNodeSelected: true,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				Tooltip: "Another Page [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				Tooltip: "Button Page [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				Tooltip: "Book Corner [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				Tooltip: "Test Page [ Page ]",
				NodeState: "Expanded",
				Icon: "icon-grid6",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "8",
				Slug: "test_page-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Collapsed",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Custom Grid Page",
				Slug: "custom_grid_page",
				NodeType: "Pagev2-grid",
				Tooltip: "Custom Grid Page [ Page ]",
				NodeState: "Expanded",
				Icon: "icon-grid6",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "5",
				Slug: "custom_grid_page-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Collapsed",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Classic Layout Page",
				Slug: "classic_layout_page",
				NodeType: "Page",
				Tooltip: "Classic Layout Page [ Classic Page ]",
				NodeState: "Expanded",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "1",
				Slug: "classic_layout_page-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Collapsed",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "A Grid Page But Hidden",
				Slug: "a_grid_page_but_hidden",
				NodeType: "Pagev2-grid",
				Tooltip: "A Grid Page But Hidden [ Page ]",
				NodeState: "Expanded",
				Icon: "icon-grid6",
				IsNodeSelected: false,
				NodeHasHiddenIndication: true,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "3",
				Slug: "a_grid_page_but_hidden-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Collapsed",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				Tooltip: "SidePanels [ Classic Side Panel ]",
				NodeState: "Collapsed",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				Tooltip: "Dialog Pages [ Classic Dialog ]",
				NodeState: "Collapsed",
				Icon: "icon-popout",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
		]);

	// Scroll and unfold few more pages
	getAppManager()
		.collapseAllNodes()
		.unfoldPageNodes(["Main Project/SidePanels/MKG", "Main Project/Dialog Pages/Help"])
		.scrollDown();

	getAppManager().unfoldWidgetContainers([
		"Main Project/SidePanels/MKG",
		"Main Project/Dialog Pages/Help",
	]);

	// Assert the information shown on App Manager.
	getAppManager()
		.getAppManagerInfo()
		.should.eql([
			{
				Name: "Main Project",
				Slug: "main_project",
				NodeType: "Pagev2-grid",
				Tooltip: "Main Project",
				NodeState: "Expanded",
				Icon: "",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "home",
				Slug: "home",
				NodeType: "Page",
				Tooltip: "home [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-home",
				IsNodeSelected: true,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Another Page",
				Slug: "another_page",
				NodeType: "Page",
				Tooltip: "Another Page [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Button Page",
				Slug: "button_page",
				NodeType: "Page",
				Tooltip: "Button Page [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Book Corner",
				Slug: "wh_subpage",
				NodeType: "Page",
				Tooltip: "Book Corner [ Classic Page ]",
				NodeState: "Collapsed",
				Icon: "icon-file2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Test Page",
				Slug: "test_page",
				NodeType: "Pagev2-grid",
				Tooltip: "Test Page [ Page ]",
				NodeState: "Collapsed",
				Icon: "icon-grid6",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "SidePanels",
				Slug: "sidepanels_1",
				NodeType: "Sidepanel",
				Tooltip: "SidePanels [ Classic Side Panel ]",
				NodeState: "Expanded",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "1",
				Slug: "sidepanels_1-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Collapsed",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "KPIs",
				Slug: "kpis_1",
				NodeType: "Sidepanel",
				Tooltip: "KPIs [ Classic Side Panel ]",
				NodeState: "Collapsed",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Filters",
				Slug: "filters_1",
				NodeType: "Sidepanel",
				Tooltip: "Filters [ Classic Side Panel ]",
				NodeState: "Collapsed",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Help",
				Slug: "help_1",
				NodeType: "Sidepanel",
				Tooltip: "Help [ Classic Side Panel ]",
				NodeState: "Collapsed",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "StoreFocus",
				Slug: "storefocus_1",
				NodeType: "Sidepanel",
				Tooltip: "StoreFocus [ Classic Side Panel ]",
				NodeState: "Collapsed",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "MKG",
				Slug: "mkg_1",
				NodeType: "Sidepanel",
				Tooltip: "MKG [ Classic Side Panel ]",
				NodeState: "Expanded",
				Icon: "icon-arrow-left7",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "2",
				Slug: "mkg_1-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Charts",
				Slug: "Charts",
				NodeType: "Widget",
				Tooltip: "Charts [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "SelectedBook_1",
				Slug: "SelectedBook_1",
				NodeType: "Widget",
				Tooltip: "SelectedBook_1 [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "Dialog Pages",
				Slug: "dialog_pages",
				NodeType: "Dialog",
				Tooltip: "Dialog Pages [ Classic Dialog ]",
				NodeState: "Expanded",
				Icon: "icon-popout",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "1",
				Slug: "dialog_pages-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Collapsed",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Help",
				Slug: "help_2",
				NodeType: "Dialog",
				Tooltip: "Help [ Classic Dialog ]",
				NodeState: "Expanded",
				Icon: "icon-popout",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "Widgets on page",
				WidgetsCount: "2",
				Slug: "help_2-widget-container",
				NodeType: "Container",
				Tooltip: "Widgets on page",
				NodeState: "Expanded",
				Icon: "aimms-cube2",
				IsNodeSelected: false,
				NodeHasHiddenIndication: false,
			},
			{
				Name: "AllSidePanels",
				Slug: "AllSidePanels",
				NodeType: "Widget",
				Tooltip: "AllSidePanels [ Widget ]",
				WidgetState: "",
			},
			{
				Name: "BookCoverImage",
				Slug: "BookCoverImage",
				NodeType: "Widget",
				Tooltip: "BookCoverImage [ Widget ]",
				WidgetState: "",
			},
		]);
});
